name: Build and release Aseprite (windows-latest)

on:
  push:
    branches:
      - main
    paths:
      - 'BuildLog.md'
  workflow_dispatch:
env:
  BUILD_TYPE: Release

jobs:
  fetch-aseprite-info:
    name: Fetch deps info
    runs-on: ubuntu-latest
    outputs:
      download-link: ${{ steps.aseprite-link.outputs.download-link }}
      release-tag: ${{ steps.aseprite-link.outputs.release-tag }}
    steps:
      - name: Fetch Aseprite release link
        id: aseprite-link
        uses: a1393323447/fetch-release@main
        with:
            group: aseprite
            repo: aseprite
            match: Aseprite-.*?-Source.zip

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: fetch-aseprite-info
    permissions:
      contents: write
    outputs:
      download-link: ${{ needs.fetch-aseprite-info.outputs.download-link }}
      release-tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          body: Aseprite-${{ needs.fetch-aseprite-info.outputs.release-tag }}
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-aseprite:
    name: Build Aseprite
    needs: create-release
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ windows-latest ]
        fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Visual Studio environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: amd64
          winsdk: 10.0.26100.0
          components: Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Microsoft.VisualStudio.Component.Windows10SDK.19041

      - name: Install Ninja
        uses: aseprite/get-ninja@main

      - name: Install Aseprite source
        shell: pwsh
        run: |
          git clone --recurse-submodules -j8 https://github.com/aseprite/aseprite --branch ${{ needs.create-release.outputs.release-tag }}
          cd aseprite
          git submodule update --init --recursive

      - name: Install Skia
        working-directory: aseprite
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip" -OutFile "Skia-Windows-Release-x64.zip"
          Expand-Archive -Path "Skia-Windows-Release-x64.zip" -DestinationPath "skia" -Force

      - name: Generating Makefiles
        shell: pwsh
        working-directory: aseprite
        run: |
          $env:enable_ccache = "off"
          $env:laf_backend = "skia"
          $env:enable_scripting = "on"
          $env:skia_arch = "x64"
          
          cmake -S . -B build -G Ninja `
            -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}" `
            -DENABLE_TESTS=OFF `
            -DENABLE_SCRIPTING="$env:enable_scripting" `
            -DENABLE_CCACHE="$env:enable_ccache" `
            -DLAF_BACKEND="$env:laf_backend" `
            -DSKIA_DIR="$((Get-Location).Path)\skia" `
            -DSKIA_LIBRARY_DIR="$((Get-Location).Path)\skia\out\Release-x64" `
            -DOPENSSL_USE_STATIC_LIBS=ON

      - name: Compiling
        shell: pwsh
        working-directory: aseprite
        run: |
          cd build
          ninja

      - name: Clean Up Build folder
        working-directory: aseprite/build/bin
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Recurse | Where-Object { $_.Name -notin @('aseprite.exe', 'data') } | Remove-Item -Recurse -Force

      - name: Make portable zip
        working-directory: aseprite/build/bin
        shell: pwsh
        run: |
          "This file is here so Aseprite behaves as a portable program" | Out-File -FilePath "aseprite.ini" -Encoding utf8

      - name: Create release zip
        working-directory: aseprite/build/bin
        shell: pwsh
        run: |
          Compress-Archive -Path * -DestinationPath "Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip" -Force

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aseprite/build/bin/Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip
          asset_name: Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip
          tag: ${{ needs.create-release.outputs.release-tag }}
